name: chat_image
description: A Package for loading an image from the web, saving it locally in the galery and showing the locally saved image.
version: 0.0.1
repository: https://github.com/Babwenbiber/flutter_chat_image

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  path_provider: ^2.0.2
  image_gallery_saver: ^1.6.9
  dio: ^4.0.0
  crypto: ^3.0.1
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
